### ISSUE TITLE
Mikrotik account setting port

### ISSUE THREAD

**Issue by sradas** [h-haghpanah/mikrotik_traffic_counter_en#3]
Hi Hesam,

I started with testing in real environment. There is different explanation for Mikrotik Accounting in your installation YT and on the Mikrotik pages.
Your setting is IP address and port 8080.
Mikrotik web access Accounting is on port 80 and URL http://router ip/accounting/ip.cgi

I can see this URL when access by web browser, as you can see in the attachment.

Could you please comment?
Thanks.
Kind regards
![MT_traffic_accounting](https://user-images.githubusercontent.com/48891626/210178221-a94ef483-7ec5-4295-9c02-9fb4e6dccb41.jpg)

**Comment by h-haghpanah** [comment]
Hi sradas 
If you successfully run flask web application you can change mikrotik accounting ip address and port on mikrotik setting on web application UI
I have a tutorial for further information , check link blow 
https://m.youtube.com/watch?v=6meppAsNaoc

Best regard, hesam

**Comment by sradas** [comment]
Hi Hesam,
It is ok, when I changed to port 80. Cool.
Solved
Thanks
